// 英文字典：key 是组件里用到的中文原文，value 是英文。
// t("中文") 在中文下原样返回；英文下查这里，命中则替换，未命中则回退中文。
// {var} 占位由 t() 的第二参数插值。新增中文文案时，记得在此补一条英文。
export const EN: Record<string, string> = {
  // ── 偏好控件 / PWA ──
  切换语言: "Switch language",
  "把「人生树」加到主屏，像 app 一样用":
    "Add Life Planner to your home screen for an app-like experience",
  "点底部分享按钮，选「添加到主屏幕」": "Tap the Share button, then “Add to Home Screen”",
  知道了: "Got it",

  // ── 引导 Onboarding ──
  "先认识一下": "First, meet ",
  真实的你: "the real you",
  "填得越具体，AI 推演的人生越像你。这些信息只存在你自己的浏览器里。":
    "The more specific you are, the more the AI's life paths feel like you. This stays only in your own browser.",
  昵称: "Name",
  年龄: "Age",
  最高学历: "Education",
  专业: "Major",
  "可选，比如 计算机 / 会计 / 临床医学": "Optional, e.g. Computer Science / Accounting / Medicine",
  现在生活在哪: "Where you live now",
  "国家/城市，用来让预测符合现实，比如 美国纽约 / 中国上海":
    "Country/city, to keep predictions realistic, e.g. New York, USA / Shanghai, China",
  "下一步 →": "Next →",
  "比如 阿明": "e.g. Alex",
  学的是什么专业: "What did you study",
  "所在国家 / 城市": "Country / city",
  现在的职业: "Your occupation",
  "可选，比如 后端工程师 / 中学老师 / 自由职业":
    "Optional, e.g. backend engineer / teacher / freelancer",
  现在靠什么谋生: "What you do for a living",
  月薪区间: "Monthly income",
  "有没有副业？": "Any side hustle?",
  有: "Yes",
  没有: "No",
  副业是什么: "What side hustle",
  "可选，比如 做自媒体 / 摆摊 / 接私活": "Optional, e.g. content creation / a stall / freelancing",
  在做的副业: "Your side hustle",
  "← 返回": "← Back",
  "情感 / 婚姻状态": "Relationship status",
  爱好: "Hobbies",
  "可选，比如 跑步、摄影、打游戏": "Optional, e.g. running, photography, gaming",
  平时喜欢做什么: "What you enjoy",
  "现在的身份 / 阶段": "Your current status / stage",
  "可选但很关键，帮预测贴合现实，比如 H1B工作签 / 在读研究生 / 已工作3年 / 创业中":
    "Optional but key — keeps predictions realistic, e.g. H-1B visa / grad student / 3 years in / building a startup",
  "你现在的处境 / 身份": "Your current situation / status",
  "你现在面临的一个岔路是？": "A crossroads you're facing right now?",
  "比如 要不要辞职创业 / 要不要换城市 / 要不要读研":
    "e.g. quit to start a company / move cities / go to grad school",
  "写下一个你正在纠结的选择，它会成为第一条岔路":
    "Write a choice you're torn over — it becomes your first branch",
  "你最近在纠结的一个选择？（可选）": "A choice you've been mulling over? (optional)",
  "可留空。写下来的话，进去后能把它变成你的第一个目标":
    "Leave it blank, or jot one down — you can turn it into your first goal inside.",
  "✨ 生成我的人生树": "✨ Generate my life tree",

  // ── 选项标签（学历/收入/情感） ──
  高中及以下: "High school or below",
  大专: "Associate",
  本科: "Bachelor's",
  硕士: "Master's",
  博士: "PhD",
  暂无收入: "No income",
  "5千以下": "< ¥5k/mo",
  "5千 - 1万": "¥5k–10k/mo",
  "1万 - 2万": "¥10k–20k/mo",
  "2万 - 5万": "¥20k–50k/mo",
  "5万以上": "> ¥50k/mo",
  单身: "Single",
  恋爱中: "Dating",
  已婚: "Married",
  已婚有孩子: "Married, with kids",
  离异: "Divorced",
  不便透露: "Prefer not to say",

  // ── 领域 / 维度 / 心情 / 走向 ──
  事业: "Career",
  财富: "Wealth",
  关系: "Relationships",
  健康: "Health",
  成长: "Growth",
  财务: "Finance",
  "感情/家庭": "Love/Family",
  居住: "Housing",
  "身份/签证": "Status/Visa",
  高光: "High",
  平稳: "Steady",
  低谷: "Low",
  乐观: "Optimistic",
  最可能: "Most likely",
  保守: "Conservative",

  // ── 人生树主界面 TreeScreen ──
  "📤 分享": "📤 Share",
  "可能的人生，不是预测的命运": "Possible lives — not a predicted fate",
  "人生树 · Life Planner": "Life Tree · Life Planner",
  "{name} 的人生树": "{name}'s Life Tree",
  "灰色虚线是维持现状，每条彩色曲线是一个不同的选择。点曲线看那段人生。":
    "The grey dashed line is the status quo; each colored curve is a different choice. Tap a curve to see that life.",
  "✨ 由真实 AI 生成": "✨ Generated by real AI",
  "＋ 添加岔路": "＋ Add a path",
  "↺ 重置": "↺ Reset",
  清空并重新开始: "Clear and start over",
  "还没有岔路。点「添加岔路」，看看另一种人生。":
    "No branches yet. Tap Add a path to explore another life.",
  "已有 {n} 条岔路 · 点曲线上的节点，还能在那里再长一条岔路":
    "{n} branch(es) so far · tap a node on a curve to grow another branch there",

  // ── 人生地图 LifeMap ──
  "{name} 的人生地图：可平移缩放，点曲线看那段人生，点节点在那里加岔路":
    "{name}'s life map: pan and zoom, tap a curve to see that life, tap a node to branch there",
  现在: "Now",
  "{age} 岁": "Age {age}",
  维持现状: "Status quo",
  "拖动平移 · 滚轮缩放 · 点曲线看那段人生 · 点节点在那里加岔路":
    "Drag to pan · scroll to zoom · tap a curve for that life · tap a node to branch",
  "＋ 在这里加岔路": "＋ Branch here",
  "＋ 在这里加岔路（{age} 岁 · {title}）": "＋ Branch here (age {age} · {title})",
  放大: "Zoom in",
  缩小: "Zoom out",
  重置视图: "Reset view",
  "{age} 岁这里": "age {age}",

  // ── 添加岔路 AddBranchSheet ──
  "{atLabel}，再选一次": "At {atLabel}, choose again",
  添加一条岔路: "Add a branch",
  "从这一刻起，如果做个不同的选择，人生会怎样？AI 会接着往下推演。":
    "From this moment, what if you chose differently? The AI continues the story from here.",
  "写下一个你想尝试的选择，AI 会推演出它的人生走向。":
    "Write a choice you want to try; the AI will play out where it leads.",
  "比如：辞职创业 / 去读研 / 搬到深圳……":
    "e.g. quit to start a company / go to grad school / move to Shenzhen…",
  "替代路 · 现实的另一种选择": "Alternative · a realistic other option",
  "疯狂路 · 不计代价、不顾眼光": "Wild card · no limits, no second-guessing",
  取消: "Cancel",
  "生成这条路 →": "Generate this path →",

  // ── 建议（替代路 / 疯狂路） ──
  辞职创业: "Quit and start a company",
  换一份更好的工作: "Find a better job",
  去读研深造: "Go to grad school",
  搬到另一座城市: "Move to another city",
  "慢下来，休息一年": "Slow down, take a year off",
  认真经营一段感情: "Invest in a relationship",
  加入一家早期创业公司: "Join an early-stage startup",
  先做副业再决定: "Try it as a side hustle first",
  拉上朋友一起干一票: "Team up with friends on a venture",
  去一线城市闯几年: "Spend a few years in a big city",
  回老家安稳发展: "Settle back in your hometown",
  出国生活一段时间: "Live abroad for a while",
  一边工作一边读在职: "Study part-time while working",
  全力备考冲名校: "Go all-in for a top school",
  出国读个学位: "Get a degree abroad",
  和现在的人定下来: "Settle down with your current partner",
  先把事业做稳再说: "Get your career stable first",
  搬到一起生活: "Move in together",
  跳去大厂: "Jump to a big tech company",
  转去更有前景的赛道: "Pivot to a more promising field",
  争取内部晋升: "Push for an internal promotion",
  裸辞去环游世界一年: "Quit and travel the world for a year",
  "All-in 创业，赌上全部积蓄": "Go all-in on a startup, betting your savings",
  "彻底转行，从零学一门新手艺": "Switch careers entirely, learn a new craft from scratch",
  搬到一个完全陌生的国家重启: "Move to a totally new country and restart",
  放下一切去追一个一直没敢碰的梦: "Drop everything to chase a dream you never dared",

  // ── 路径详情 PathDetail ──
  "这条路找不到了。": "This path is gone.",
  "← 返回人生树": "← Back to the tree",
  "{name} 的综合人生指数 ·": "{name}'s overall life index ·",
  "这是一种可能的人生，不是预测。数字代表综合状态感受，仅供想象与参考。":
    "This is one possible life, not a prediction. The number is a felt overall state — for imagination only.",
  "✨ 和 {age} 岁的你聊聊": "✨ Talk to you at {age}",
  换个走向看看: "Try another trajectory",
  各方面随时间的变化: "How each area changes over time",
  这条路上的关键时刻: "Key moments on this path",
  "✏️ 不太对？补充信息重推": "✏️ Not right? Add info & re-run",
  "补充信息，重新推演": "Add info & re-run",
  "哪里不对、漏说了什么？写下来，AI 会据此修正时间线重新推演。":
    "What's off or missing? Note it and the AI will fix the timeline and re-run.",
  "比如：我已经拿到 offer，23 岁就入学，不用备考":
    "e.g. I already have an offer, I start at 23, no test prep needed",
  "重新推演 →": "Re-run →",

  // ── 和未来的自己聊聊 FutureSelfChat ──
  "和 {age} 岁的你聊聊": "Talk to you at {age}",
  关闭: "Close",
  "问问那个走了这条路的你…": "Ask the you who took this path…",
  "对方正在回想…": "They're thinking back…",
  "（没接上 AI，先聊不了——确认 .env.local 里配了 DEEPSEEK_API_KEY）":
    "(No AI connected — set DEEPSEEK_API_KEY in .env.local)",
  "🔄 据我们聊的，重推这条路": "🔄 Re-run this path from our chat",
  "会把你在这里说的补充给未来的自己，重新推演这条路。":
    "Sends what you said here to your future self and re-runs this path.",
  "把「{label}」当作一个新选择？": "Make “{label}” a new choice?",
  "🌱 已把「{label}」加进你的人生树": "🌱 Added “{label}” to your life tree",
  "＋ 加进人生树": "＋ Add to tree",
  "跟 {age} 岁的自己说点什么…": "Say something to your {age}-year-old self…",
  发送: "Send",
  "你后悔走这条路吗？": "Do you regret this path?",
  "当时最难的坎是怎么熬过来的？": "How did you get through the hardest part?",
  给现在的我一句话: "One line for the me of today",
  "有没有我没考虑过的路？": "Any path I haven't considered?",

  // ── 规划助手 PlanningAssistant ──
  "💬 规划助手": "💬 Planner",
  规划助手: "Planner",
  收起: "Collapse",
  "迷茫的时候，跟我说说你在纠结什么。我会帮你理清，也会提一些你没想到的路。":
    "When you feel lost, tell me what you're torn over. I'll help untangle it and suggest paths you haven't thought of.",
  "助手正在想…": "Thinking…",
  "（没接上 AI——确认 .env.local 配了 DEEPSEEK_API_KEY）":
    "(No AI connected — set DEEPSEEK_API_KEY in .env.local)",
  "正在铺开几条路…": "Laying out a few paths…",
  "给你铺开几条路（点「画这条」才会加到地图）":
    "A few paths for you (tap Draw this to add it to the map)",
  全部画上: "Draw all",
  "🕒 分叉时机由 AI 按现实推演决定": "🕒 Fork timing decided by the AI",
  "✓ 已画": "✓ Drawn",
  "＋ 画这条": "＋ Draw this",
  "✨ 帮我铺开几条值得探索的路": "✨ Suggest a few paths worth exploring",
  "正在铺开…": "Laying out…",
  "🌱 已加进人生树：{label}": "🌱 Added to your tree: {label}",
  "🎯 设成目标": "🎯 Make it a goal",
  "🎯 已设成目标": "🎯 Added as goal",
  "🎯 已设成目标：{label}": "🎯 Added as goal: {label}",
  "加「{label}」当一条新岔路？": "Add “{label}” as a new branch?",
  "＋ 加进树": "＋ Add to tree",
  "说说你在纠结什么…": "Tell me what you're torn over…",
  "我有点迷茫，帮我理理我现在的选择": "I feel a bit lost — help me sort out my options",
  "我还有哪些没想到的路？": "What paths haven't I thought of?",
  "这几条路各自最大的风险是什么？": "What's the biggest risk of each path?",

  // ── 推演动画 PredictionOverlay ──
  "正在推演你的人生地图…": "Mapping out your life…",
  "正在推演这条路…": "Playing out this path…",
  正在结合你的真实处境逐条推演: "Reasoning through your real situation, step by step",
  正在依据你填写的信息逐条推演: "Reasoning through what you entered, step by step",
  读取此刻的你: "Reading the you of now",
  寻找现实里的转折点: "Finding the real turning points",
  推演十年后的样子: "Projecting ten years out",
  "校对签证 / 薪资 / 城市的可信度": "Checking visa / salary / city realism",
  把每条时间线画出来: "Drawing each timeline",
  "已推演 {done} / {total} 条路": "Predicted {done} / {total} paths",
  "正在推演，请稍候": "Predicting, please wait",
  "AI 正在推演你的人生": "AI is predicting your life",

  // ── 决策闭环（选定/落地/复盘） ──
  "把这条路变成计划": "Turn this path into a plan",
  "你的决定": "Your decision",
  "为什么选它": "Why this choice",
  "你预期会发生什么": "What do you expect to happen",
  "信心几成": "How confident are you",
  "这个决定可逆吗？": "Is this reversible?",
  "单行道": "One-way door",
  "可回头": "Two-way door",
  "多久后回看": "When to review",
  "30 天": "30 days",
  "90 天": "90 days",
  "生成计划 →": "Generate plan →",
  "正在为你制定计划…": "Building your plan…",
  "近期行动": "Next actions",
  "低成本试错": "Cheap experiments",
  "完成": "Done",
  "已复盘": "Reviewed",
  "比预期差": "Worse than expected",
  "和预期差不多": "About as expected",
  "比预期好": "Better than expected",
  "（没接上 AI，先用本地模板生成的计划）": "(No AI — generated a local template plan)",
  "距复盘还有 {n} 天": "{n} days until review",
  "有 {n} 个决定该复盘了": "{n} decision(s) ready to review",
  "去复盘": "Review",
  "复盘：{label}": "Review: {label}",
  "实际发生了什么？": "What actually happened?",
  "比预期差很多": "Much worse than expected",
  "比预期好很多": "Much better than expected",
  "当时你预期：{exp}": "You expected: {exp}",
  "当时信心 {n}%": "Confidence was {n}%",
  "完成复盘": "Finish review",
  "用真实情况再推演一条": "Re-run a prediction from reality",
  "想清楚这个决定": "Think this decision through",
  "后悔最小化：80 岁回头看，哪个更不后悔？": "Regret minimization: at 80, which will I regret less?",
  "预演失败：三年后它失败了，最可能因为什么？": "Pre-mortem: if it fails in 3 years, why?",
  "可逆性：这是单行道还是可回头？": "Reversibility: one-way or two-way door?",

  // ── 日历规划首页 CalendarPlannerScreen / MonthCalendar ──
  规划: "Plan",
  "{y}年 {m}月": "{y}-{m}",
  回到今天: "Today",
  上个月: "Previous month",
  下个月: "Next month",
  "周{w}": "{w}",
  "未排期 · 拖到某天，或点一下再点日子": "Unscheduled · drag to a day, or tap then tap a day",
  点一个日子放下它: "Tap a day to drop it",
  没有未排期的行动: "No unscheduled actions",
  "{d} 这天": "{d}",
  "这天还没有安排。把未排期的行动拖/点过来。": "Nothing on this day yet. Drag or tap an unscheduled action here.",
  移回未排期: "Move back to unscheduled",
  目标: "Goals",
  "还没有长期目标。去「我的规划」加一个。": "No long-term goals yet. Add one in My plan.",
  "未来预测 ·「你在这里」随里程碑前进": "Forecast · “you are here” advances with milestones",

  // ── 激励闭环 / 仪表盘 v2 ──
  今天: "Today",
  "连续 {n} 天": "{n}-day streak",
  最近完成情况: "Recent activity",
  "看完整人生树 →": "See full life tree →",
  "你真的做到了：{title}": "You actually did it: {title}",
  和未来的你说一声: "Tell your future self",
  今日计划: "Today's plan",
  "✨ 建议今天做什么": "✨ Suggest today's focus",
  "正在想…": "Thinking…",
  "今天还没安排。让 AI 建议，或去「我的规划」把目标的行动挑进今天。":
    "Nothing planned yet. Let AI suggest, or pick actions into today from My plan.",
  "建议今天做这几件（点「加入今天」）": "Suggested for today (tap “Add to today”)",
  "＋ 加入今天": "+ Add to today",
  你的人生树: "Your life tree",
  "「你在这里」会随你完成里程碑前进；每日习惯不移动它。": "“You are here” advances as you complete milestones; daily habits don’t move it.",
  "还没有路。去「我的规划」加一个长期目标，它会在树上长出一条路。":
    "No paths yet. Add a long-term goal in My plan and it grows a branch here.",
  你在这里: "You are here",
  "← 今日": "← Today",
  "＋今天": "+ Today",
  "🔁重复": "🔁 Repeat",
  "🔁每天": "🔁 Daily",
  "🔁每周": "🔁 Weekly",
  从今天移除: "Remove from today",

  // ── 规划主线 PlanScreen ──
  "重新拆解会覆盖现有行动（包括已设的重复和完成状态）。继续？": "Re-breaking will replace the current actions (including repeat flags and done state). Continue?",
  "🎯 我的规划": "🎯 My Plan",
  我的规划: "My Plan",
  "先定长期目标——它会在你的人生树上长出一条路；用短期目标和行动一步步逼近它。":
    "Set a long-term goal — it grows a path on your life tree; close in on it with short-term goals and actions.",
  "该回看目标了：有 {n} 个目标一周没动过了。":
    "Time to review: {n} goal(s) haven't moved in a week.",
  我回看过了: "I've reviewed",
  "✨ 帮我想几个目标": "✨ Suggest some goals",
  "正在想几个适合你的目标…": "Thinking of goals that fit you…",
  "把「{label}」设成第一个长期目标": "Make “{label}” your first long-term goal",
  "点「加入」才会进规划（长期目标会在树上长出一条路）":
    "Tap “Add” to put it in your plan (a long-term goal grows a path on the tree)",
  长期: "Long-term",
  短期: "Short-term",
  "✓ 已加入": "✓ Added",
  加入: "Add",
  长期目标: "Long-term goals",
  短期目标: "Short-term goals",
  "进度 {pct}%": "{pct}% done",
  "📈 在树上看这条路": "📈 See this path on the tree",
  "✨ 和达成目标的未来的你聊聊": "✨ Talk to the future you who got there",
  "加一个短期目标（踏脚石）": "Add a short-term goal (stepping stone)",
  "正在拆解…": "Breaking it down…",
  "✨ 拆成行动": "✨ Break into actions",
  "✅ 已达成": "✅ Achieved",
  移除: "Remove",
  "确定移除这个目标？长期目标会连同它在树上的分支一起删除。":
    "Remove this goal? A long-term goal also deletes its branch on the tree.",
  已达成的里程碑: "Milestones reached",
  "已达成 · {area}+": "Achieved · {area}+",
  "还没有目标。让 AI 帮你想几个，看着它们在你的人生树上长出来。":
    "No goals yet. Let the AI suggest some, and watch them grow on your life tree.",

  // ── 引导 step 2：技能 / 财务 / 家庭 / 风险 ──
  "再多说说你自己（可选，但越填越准）": "A bit more about you (optional, the more the better)",
  "技能 / 专长": "Skills / strengths",
  "比如 编程、设计、英语、带团队": "e.g. coding, design, English, leading a team",
  "存款": "Savings",
  "负债": "Debt",
  "资产": "Assets",
  "比如 一套房、一辆车、些许股票": "e.g. an apartment, a car, some stocks",
  "家庭责任": "Family responsibility",
  "风险偏好": "Risk appetite",
  "(暂不填)": "(skip)",
  "几乎没有积蓄": "Almost no savings",
  "1万以下": "< ¥10k",
  "1万 - 10万": "¥10k – 100k",
  "10万 - 50万": "¥100k – 500k",
  "50万 - 100万": "¥500k – 1M",
  "100万以上": "> ¥1M",
  "没有负债": "No debt",
  "10万以下": "< ¥100k",
  "暂无特别负担": "None in particular",
  "要养孩子": "Raising kids",
  "要养父母": "Supporting parents",
  "上有老下有小": "Kids and parents to support",
  "保守求稳": "Play it safe",
  "稳健": "Balanced",
  "进取敢冲": "Bold, go for it",

  // ── 本周回顾 WeeklyReviewSheet ──
  "📅 本周回顾": "📅 Weekly Review",
  本周回顾: "Weekly Review",
  "本周完成 {n} 件 · 活跃 {d} 天 · 🔥连续 {s} 天":
    "{n} done this week · {d} active days · 🔥{s}-day streak",
  本周达成: "Achieved this week",
  该回看的目标: "Goals to revisit",
  我都回看过了: "All reviewed",
  该复盘的决定: "Decisions to review",
  // 去复盘 and 关闭 already exist above (decisions + FutureSelfChat sections)
  "停下来看看走过的一周，比一直往前更重要。":
    "Pausing to reflect on the week matters more than always pushing forward.",

  // ── 危机关怀覆层 SafetyCare ──
  "听起来你正在经历很难熬的时刻，我很在意你。比起聊未来，现在更重要的是你的安全。":
    "It sounds like you're going through something really painful, and I care about that. Right now your safety matters more than talking about the future.",
  "如果你愿意，我随时在这里。": "I'm here whenever you're ready.",
  "先停一下，照顾好自己": "Take a moment — look after yourself",
  "看起来你正在经历很艰难的时刻。你的感受很重要，也值得被认真对待。预测未来可以晚点再说——此刻，先和能帮到你的人聊聊。":
    "It looks like you're going through something really hard right now. What you feel matters and deserves to be taken seriously. The future can wait — for now, please reach out to someone who can help.",
  "可以联系：": "You can reach:",
  "我没事，继续": "I'm okay, continue",

  // ── 应用外壳 / 侧栏导航 AppShell ──
  人生树: "Life Tree",
  日历: "Calendar",
  // 目标 already exists above (CalendarPlannerScreen section)
  习惯: "Habits",
  人生面: "Life Areas",
  洞察: "Insights",
  重置: "Reset",
  打开菜单: "Open menu",
  // 关闭 already exists above (FutureSelfChat section)
  这一块马上就好: "This part is coming right up",

  // ── 人生面 AreasSection ──
  "五个维度的现状与目标——看清自己在哪里，想去哪里。":
    "Five dimensions, your status and goals — see where you are and where you want to go.",
  还没有目标: "No goals yet",
  去规划: "Plan now",
  "{n} 个习惯": "{n} habit(s)",
  "各个维度还没有目标，去规划一个吧。": "No goals in any area yet — go set one.",

  // ── 洞察 InsightsSection ──
  "过去 90 天的行动轨迹与坚持力量": "Your action trail and consistency over the last 90 days",
  当前连续: "Current streak",
  最长连续: "Longest streak",
  近90天完成: "Done (90 days)",
  活跃天数: "Active days",
  坚持度: "Consistency",
  "近 90 天完成热力图": "90-day completion heatmap",
  "还没有记录。完成一些行动，这里就会亮起来。": "No record yet. Complete some actions and this will light up.",
  无记录: "None",
  "1 件": "1",
  "2 件+": "2+",
  "{n} 天": "{n}d",
  "{n} 件": "{n}",

  // ── 收件箱 InboxSection ──
  "收件箱": "Inbox",
  "想到什么先丢进来，回头再归类。": "Capture anything here first, sort it out later.",
  "随手记一条…": "Jot something down…",
  "快速捕获": "Quick capture",
  "添加": "Add",
  "提示：设成长期目标会在你的人生树上长出一条新的路（预测树枝）。":
    "Tip: making it a long-term goal grows a new branch on your life tree (prediction path).",
  "收件箱是空的。想到什么先丢进来，回头再归类。":
    "Your inbox is empty. Capture anything that comes to mind — sort it out later.",
  "🎯 设成长期目标": "🎯 Make long-term goal",
  "设成短期目标": "Make short-term goal",
  "删除": "Delete",

  // ── 目标截止日 deadline display ──
  "截止": "Due",
  "剩 {n} 天": "{n}d left",
  "今天截止": "Due today",
  "逾期 {n} 天": "{n}d overdue",

  // ── 习惯 HabitsSection ──
  "坚持重复，构成你真正的生活方式。": "Repeat consistently — that's what shapes your real lifestyle.",
  "还没有习惯。去「我的规划」把某条行动设成每天或每周重复。":
    "No habits yet. Go to My Plan and set an action to 🔁 daily or weekly repeat.",
  每天: "Daily",
  每周: "Weekly",
  "🔥 连续 {n}": "🔥 {n}-day streak",
  "🔥 连续 {n} 天": "🔥 {n}-day streak",
  "🔥 连续 {n} 周": "🔥 {n}-week streak",
};
